/*
 * Department Transports Api
 *
 * Department Transports management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsuchy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package xsuchy_ambulance

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type DepartmentListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateDepartment - Creates a new department
   CreateDepartment(ctx *gin.Context)

    // GetAllDepartments - Provides the list of all departments
   GetAllDepartments(ctx *gin.Context)

    // GetDepartment - Provides details about a specific department
   GetDepartment(ctx *gin.Context)

 }

// partial implementation of DepartmentListAPI - all functions must be implemented in add on files
type implDepartmentListAPI struct {

}

func newDepartmentListAPI() DepartmentListAPI {
  return &implDepartmentListAPI{}
}

func (this *implDepartmentListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/departments/:departmentId", this.CreateDepartment)
  routerGroup.Handle( http.MethodGet, "/departments", this.GetAllDepartments)
  routerGroup.Handle( http.MethodGet, "/departments/:departmentId", this.GetDepartment)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateDepartment - Creates a new department
// func (this *implDepartmentListAPI) CreateDepartment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetAllDepartments - Provides the list of all departments
// func (this *implDepartmentListAPI) GetAllDepartments(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetDepartment - Provides details about a specific department
// func (this *implDepartmentListAPI) GetDepartment(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

