/*
 * Department Transports Api
 *
 * Department Transports management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsuchy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package xsuchy_ambulance

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type MobilityStatusListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // GetMobilityStatusList - Provides the list of mobility statuses
   GetMobilityStatusList(ctx *gin.Context)

 }

// partial implementation of MobilityStatusListAPI - all functions must be implemented in add on files
type implMobilityStatusListAPI struct {

}

func newMobilityStatusListAPI() MobilityStatusListAPI {
  return &implMobilityStatusListAPI{}
}

func (this *implMobilityStatusListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/mobility-status", this.GetMobilityStatusList)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetMobilityStatusList - Provides the list of mobility statuses
// func (this *implMobilityStatusListAPI) GetMobilityStatusList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

