/*
 * Department Transports Api
 *
 * Department Transports management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsuchy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xsuchy_ambulance

import (
	"time"
)

type Transport struct {

	// Unique ID of the transport in this transport list
	Id string `json:"id"`

	// Unique identifier of the patient - birth number
	PatientId string `json:"patientId"`

	// Name of patient in transports list
	PatientName string `json:"patientName"`

	// ID of the department from where the patient is being transported
	FromDepartmentId string `json:"fromDepartmentId"`

	// ID of the department to where the patient is being transported
	ToDepartmentId string `json:"toDepartmentId"`

	// Scheduled time of the transport
	ScheduledDateTime time.Time `json:"scheduledDateTime"`

	// Estimated duration of the transport in minutes
	EstimatedDurationMinutes int32 `json:"estimatedDurationMinutes"`

	MobilityStatus MobilityStatus `json:"mobilityStatus"`
}
