/*
 * Department Transports Api
 *
 * Department Transports management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsuchy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xsuchy_ambulance

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newDepartmentListAPI()
    api.addRoutes(group)
  }
  
  {
    api := newDepartmentTransportsListAPI()
    api.addRoutes(group)
  }
  
  {
    api := newMobilityStatusListAPI()
    api.addRoutes(group)
  }
  
}